PROJECT = 6lowpan-nd-rpl

WITH_SHELL=1
WITH_UDPCLIENT=1
WITH_CUSTOMRDC=1
WITH_SMARTLED=1

APPS = collect-view

PROJECTDIR=..
CONTIKI = ../../..

CONTIKI_TARGET_MAIN = contiki-z1-main-sleepy.c

include $(PROJECTDIR)/Makefile

